<?php
defined('BASEPATH') OR exit('No direct script access allowed');
require(APPPATH .'third_party\fpdf\fpdf.php');
require(APPPATH . 'third_party\PHPExcel.php');
class PDF extends FPDF
{
	function Footer()
   {
        $this->SetY(-10);
        $this->SetFont('Courier', '', 7);
        $this->Cell(0,10,'Page '.$this->PageNo().' of {nb}', 0, 0, 'R');
   }
}

class PdfReportModel extends CI_Model {

	public function __construct()
	{
		parent::__construct();
			
		date_default_timezone_set('Asia/Colombo');	
	}
	
	private function _initiate_DB_connection(){
		$ip =   "172.20.100.237";
		exec("ping -n 1 $ip", $output, $status);
		if($status==0)
		{
			$this->DB2 = $this->load->database('oracle', TRUE);
			
			 if(!$this->DB2 ->initialize())
			 {
				$this->load->database('oracle', false);
				$this->session->set_flashdata('fail', ' ** Error -  Could Not Connect To CBS Database **');
				header( 'Location: '.base_url("index.php/printReport") ) ;
			 } 	 
		}
		else
		{
			$this->load->database('oracle', false);
			$this->session->set_flashdata('fail', ' ** Error -  Could Not Connect To CBS Database **');
			header( 'Location: '.base_url("index.php/printReport") ) ;	
		}
	}
	
	
	
	
	function printPDF($selectedDate){
		$totalAmount = 0; 
		
		$indexNumber = 1;
		$dayBeforeSelectedDate = date('Y-m-d', strtotime($selectedDate . ' -1 day'));

		$this->db->trans_begin();

		$this->db->select("save_time.previousdaytime, save_time.currentdaytime");
		$this->db->from('save_time');
		$query_time = $this->db->get();

		$time_row = $query_time->row(); 
		$previousdaytime = $time_row->previousdaytime;
		$currentdaytime = $time_row->currentdaytime;
			
		
		$pdf = new PDF('L','mm','A4');
		$pdf -> AddPage();
		$pdf->AliasNbPages();
		$pdf -> setDisplayMode ('fullpage');
		$pdf->SetAutoPageBreak(true,8);
		
		
		$pdf->SetFont('Courier','',7);
		$pdf->SetXY(10, 0);
		$pdf->Cell(10, 5, "Report Generated By : ".$this->session->userdata('user_name'), 0, 1, 'L'); 
		$pdf->SetXY(0, 0);
		$pdf->Cell(0, 5, "Report Generated Date : ".date('Y-m-d H:i:s'), 0, 1, 'R');
		
		$pdf->SetFont('Courier','B',12);

		$pdf->Cell(0 ,5,"Regional Development Bank",0,1,'C');
		$pdf->SetFont('Courier','',10);
		$pdf->Cell(0, 4, "", 0, 1);
		//$pdf->Cell(0 ,4,"Business Operation Unit",0,1,'C');
		$pdf->Cell(0 ,4,"QR & Justpay Transaction Report  ".$selectedDate,0,1,'C');
		
		$pdf->Cell(0 ,3,"",0,1,'C');
		$pdf->Cell(0 ,4,"Auto Reversal Failed  " .$dayBeforeSelectedDate." ".$previousdaytime. "  To  " .$selectedDate." ".$currentdaytime ,0,1,'C');
		
		$pdf->Cell(0 ,3,"",0,1,'C');
		
		
		$this->db->trans_begin();

	    $this->db->select("save_time.previousdaytime, save_time.currentdaytime");
        $this->db->from('save_time');
        $query_time = $this->db->get();

        $time_row = $query_time->row();
        $previousdaytime = $time_row->previousdaytime;
        $currentdaytime = $time_row->currentdaytime;

        $dayBeforeSelectedDate = date('Y-m-d', strtotime($selectedDate . ' -1 day'));

		$previousdatetime=$dayBeforeSelectedDate. " " . $previousdaytime;

		$currentdatetime=$selectedDate. " " . $currentdaytime;

        $this->db->select('reconfile_v.Response_Code,
		reconfile_v.Amount,
		reconfile_v.Time,
		reconfile_v.RRN,
		reconfile_v.Account_Number,Branch_Name,Bank_Name', false);
		$this->db->from('reconfile_v');
        $this->db->join( 'trn_log_justpay_registration_view','trn_log_justpay_registration_view.RRN = reconfile_v.RRN', 'left');
        $this->db->where("reconfile_v.Time BETWEEN '". $previousdatetime ."' AND '" . $currentdatetime."'");
		$this->db->where('trn_log_justpay_registration_view.RRN IS NULL AND reconfile_v.Response_Code=3');
		$this->db->order_by('reconfile_v.Time');
		$query = $this->db->get();
			
		$pdf->SetFont('Courier','',8);
		$pdf ->SetLineWidth(0.1);
	    $pdf->Cell(5 ,4,'No',1,0,'C');
		$pdf->Cell(60 ,4,'Customer Name',1,0,'C');
		$pdf->Cell(25 ,4,'Account No',1,0,'C');
        $pdf->Cell(35 ,4,'Branch Name',1,0,'C');
        $pdf->Cell(35 ,4,'Trnx Date & Time ',1,0,'C');
        $pdf->Cell(15 ,4,'To Bank',1,0,'C');
		
		$pdf->Cell(25 ,4,"Trnx Amount",1,0,'C');
		
		$pdf->Cell(20 ,4,'App Name ',1,0,'C');
		$pdf->Cell(35 ,4,"Feedback",1,1,'C');
		
        $this->_initiate_DB_connection();
		

			
			
		foreach ($query->result_array() as $row) 
		{

            $this->DB2->select("RDB_CC_CLIENTS_V.ALPHA_ID,RDB_CC_CLIENTS_V.LAST_NAME");
			
			$this->DB2->from("RDB_CC_ACCTS_V");
			$this->DB2->join("RDB_CC_CLIENTS_V" , "RDB_CC_CLIENTS_V.CLIENTS_CODE = RDB_CC_ACCTS_V.CLIENT_NO",'inner');
			$this->DB2->where("RDB_CC_ACCTS_V.ACCT_NO = '".$row['Account_Number']."'");
			$query_2 = $this->DB2->get();

			$customer_name_full = $query_2->row()->ALPHA_ID." ".$query_2->row()->LAST_NAME;
			
			$customer_name = substr($customer_name_full, 0, 33);



			$pdf->Cell(5 ,4,$indexNumber,1,0,'C');
			$pdf->Cell(60,4,$customer_name,1,0,'L');
			$pdf->Cell(25,4,$row['Account_Number'],1,0,'C');
            $pdf->Cell(35 ,4,$row['Branch_Name'],1,0,'L');
            $pdf->Cell(35 ,4,$row['Time'],1,0,'C');
            $pdf->Cell(15 ,4,$row["Bank_Name"],1,0,'L');
	        $pdf->Cell(25 ,4,$row['Amount'],1,0,'R');
			$pdf->Cell(20 ,4,"",1,0,'C');
			$pdf->Cell(35 ,4,"Sill not reverse",1,1,'C');
			$totalAmount +=  $row['Amount'];
			$indexNumber++;
		}

$pdf->SetFont('','B');
		$pdf->Cell(175, 4, "Total Amount", 1, 0, 'R');
		$pdf->Cell(25, 4, number_format($totalAmount, 2), 1, 1, 'R');
		$pdf->SetFont('','');

		$pdf->Cell(149, 8, "", 0, 1);

		$pdf->Cell(0 ,4,"please make necessary arrangements to credit said transaction as mentioned above and debit 240105120 - QR control A/C with Rs.".number_format($totalAmount, 2),0,1,'L');
		
		$pdf->Cell(149, 12, "", 0, 1);

		$pdf->Cell(10, 4,"", 0, 0 ,'C');
		$pdf->Cell(25, 4,"......................", 0, 0 ,'C');
		$pdf->Cell(80, 4,"", 0, 0);
		$pdf->Cell(25, 4,"......................", 0, 0,'C');
		$pdf->Cell(80, 4,"", 0, 0);
		$pdf->Cell(25, 4,"......................", 0, 1,'C');


		$pdf->Cell(10, 4,"", 0, 0 ,'C');
		$pdf->SetFont('','B');
		$pdf->Cell(25, 4,"prepared by", 0, 0, 'C');
		
		$pdf->Cell(80, 4,"", 0, 0);
		$pdf->Cell(25, 4,"Checked by", 0, 0, 'C');
		$pdf->Cell(80, 4,"", 0, 0);
		$pdf->Cell(25, 4,"Authorized by", 0, 1, 'C');


		$pdf->Cell(10, 4,"", 0, 0 ,'C');
		$pdf->SetFont('','');
		$pdf->Cell(25, 4,"Banking Assistant", 0, 0, 'C');
		$pdf->Cell(80, 4,"", 0, 0);
		$pdf->Cell(25, 4,"Digital Banking Unit - Manager", 0, 0, 'C');
		$pdf->Cell(80, 4,"", 0, 0);
		$pdf->Cell(25, 4,"Assistent General Manager - Operation", 0, 1, 'C');
				
		$pdf -> output ('QR & Justpay Transaction Report '.$selectedDate.'pdf','I'); 
	
	}
	
	
}


